version: '3'
services:
  notebook:
    image: marcioaug/intel-anaconda-full
    volumes:
      - ..:/opt/src
      - ./jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
    ports:
      - "8888:8888"
    working_dir: /opt/src
    entrypoint: |
      bash -c 'bash -s << EOF
        source activate idp
        jupyter notebook --no-browser --notebook-dir=/opt/src --ip=0.0.0.0 --allow-root
      EOF'
